### ISSUE TITLE
Options menu

### ISSUE THREAD

**Issue by osbornejr** [lusakasa/saka#23]
It would be nice if Saka was as customisable as Saka key.  Some things that could be available in an options menu:

- choose which mode is the default/ ability to have separate shortcuts to access each mode directly
- hide the full list of tabs/bookmarks (i.e. just the search bar until some input is typed) 
- colour of bar and text etc.
- a full list of available shortcuts

Apologies if this already exists.

**Comment by pureooze** [comment]
This is definitely something on the todo list, I want users to be able to change settings like hotkeys, default mode, etc. 

Also, you should be able to access each mode directly using the hotkeys listed in the 'modes' mode.
![image](https://user-images.githubusercontent.com/2337524/38768580-1e9add3a-3fc4-11e8-959c-c65956b9dbee.png)

**Comment by pureooze** [comment]
@osbornejr I have added the features mentioned in #24 to Saka. It is currently on a branch since I still need to make some more unit tests but should be merged into master soon at which point I will make the 0.13.0 release.

In the meantime feel free to play around with it by cloning [my saka repo](https://github.com/pureooze/saka/tree/options-page) on the options-page branch and then following the instructions to setup the project locally.

**Comment by osbornejr** [comment]
Fantastic! I will have a look at that when I get a chance.

Thanks

**Comment by pureooze** [comment]
I have released the 0.13.0 release of saka so you should be able to use it after downloading the update.

**Comment by pureooze** [comment]
A full list of the available hotkeys can now be viewed on the Saka options page (feature has not been released yet but is in master).

![image](https://user-images.githubusercontent.com/2337524/39681340-921a7eb8-5177-11e8-9657-40a068e9cbf5.png)

**Comment by pureooze** [comment]
Made a new issue for the color scheme ask (https://github.com/lusakasa/saka/issues/57). Closing this issue.
