### ISSUE TITLE
browser.tabs is undefined

### ISSUE THREAD

**Issue by ris58h** [lusakasa/saka#60]
I've just installed Saka for Firefox and couldn't toggle the panel (CTRL+SPACE Am I right?). When I press extension's icon (browser_action) I get 'browser.tabs is undefined' in the current page console.

Saka 0.4.0
Saka Key 1.25.2
Firefox 61.0.1
OS Ubuntu 18.04

**Comment by pureooze** [comment]
We had an issue with the mozilla addons site disabling the newer versions so it defaulted to the old 0.4.0 version. It should be fixed now. Can you try installing the latest version (0.15.3) from https://addons.mozilla.org/en-US/firefox/addon/saka

Note that it may take a bit before the version becomes available on the site since I just uploaded it.

**Comment by ris58h** [comment]
@pureooze It works now.
