### ISSUE TITLE
Modes ui

### ISSUE THREAD

**Issue by rayman89** [lusakasa/saka#64]
What about having the modes accessible at all time like this?

![image](https://user-images.githubusercontent.com/5449042/43142526-3e30d93e-8f1e-11e8-9e56-b6efe8852088.png)

I think that would make the addon a lot more dynamic and comfortable.

I think it would be also nice to have an "x" button on the top left corner to close the UI whenever you want.

**Comment by pureooze** [comment]
I like the idea of having all the mods accessible at once 👍. This could make Saka easier to use (I feel like a lot of users aren't aware they can switch modes). I'll try messing around with the layout when I get time, this should be pretty simple to implement.

**Comment by pureooze** [comment]
I have created a prototype UI of this. Still need to do some fine tuning with the CSS but its getting there :smile: 

![mode-selector](https://user-images.githubusercontent.com/2337524/43549184-fbc35a4a-95ad-11e8-842d-37e1d6e4c750.png)

**Comment by eejdoowad** [comment]
Can this menu’s position and visibility be configurable from the options page?

Some users might not want it, and other might want it above the search bar or below the list of results.

**Comment by pureooze** [comment]
So my personal opinion is that we should be careful with how much customization we allow for in the UI. I understand that some users may not like the look but giving options for everything puts a larger burden on us to test all the different variations of options. I would rather focus on just making the menu non-intrusive so if users don't want to use it, it shouldn't get in their way from using Saka.

The footer is a good example of this. I would rather not make its position customizable because I don't see the value being worth the cost. Sure some users may not like it but that will be true of any UI. Allowing for it to move around adds more complexity to the code without (IMO) providing any real value.

So if there is something you don't like about this implementation what can we change to improve it? Would it be better as a vertical sidebar? Or maybe placed on the bottom instead of the top? I'm open to feedback but I would prefer to just have one implementation rather than having to deal with customization options.

As a side note, one idea I had to improve the usability of this was to allow users to switch between the tabs using the arrow keys (or some other key combo since arrow keys are useful in the search bar) instead of having to remember the specific shortcut for each mode. We could also switch out the icons with the full hotkey for a mode when we detect the user presses `ctrl`. This way users could see what the hotkey is for all the modes and then pick whichever one they wanted to switch to. Thoughts?

**Comment by rayman89** [comment]
I like it how it's on the prototype. Maybe the icons could be bigger but that's just personal preference Adding hotkeys for a button that you can easily click is not necessary in my opinion.  There are a ton of hotkeys for this addon IMO I don't think users are going to be using them all. I think its better to have a few memorable useful hotkeys.

**Comment by eejdoowad** [comment]
The codebase has remnants of a mode selection toolbar like the one discussed. I decided to cut it out because:

1. The extra menu stole attention away from the search UI. I tried to mitigate this by making it small and faded gray like the footer.
2. Physically separating the search term and its results interferes with my mental association of them. Basically, proximity implies a relationship.
2. It makes scanning the results more difficult since they are further from the search bar.

I still think a mode selection toolbar would be really helpful, especially for new users. And now that you mention it, it would be good to avoid cluttering the configuration with a billion options. But it would be really nice to have an on/off switch for this toolbar.

Keyboard shortcuts would also be helpful. The hard part is finding something that is both intuitive and not already taken.

Showing different options when a modifier key is pressed is an awesome idea. You could even apply this to the result items, e.g. highlight the active result red when the ctrl key is pressed and delete them it if the user then presses enter.

**Comment by rayman89** [comment]
I think making things not visible in the first place was the problem. If you use a modifier key to show part of the UI it would make it less intuitive than before IMO. You can have a +/- button if you cant to expand/contract the toolbar but I dont see how it would be bothersome to have it for the majority of users.

**Comment by pureooze** [comment]
@eejdoowad 
What about placing it above the search bar? That way the proximity relationship between the search bar and the results is untouched and there is no visual interruption when scanning for results.

@rayman89 
>I think making things not visible in the first place was the problem

Can you clarify what you mean by this? You mean the hotkeys for each mode being hidden until the modifier is pressed? I guess as a new user its hard to know what magic key you need to press to see more information in the UI.

**Comment by eejdoowad** [comment]
Top advantage: familiar layout that is similar to browser’s tab and url bar

Right advantage: users’ initial focus is drawn to the search bar

Pick your favorite 🙂

**Comment by pureooze** [comment]
So I tried it on the RHS and LHS but the problem with making it a column is that the height of the GUIContainer changes based on how many search results there are which causes the column to resize constantly. One workaround would be to have a fixed size for the column so it never changes size but I dont think its worth it.

Instead I went with putting it at the top. I added a small border to the top of the tab (the color changes based on the mode you select). This is similar to how Firefox shows the difference it the browser tabs. There is also a contrast between selected/unselected tabs so that should help differentiate it for users. It seems to look pretty good to me. Thoughts @rayman89 @eejdoowad ?

![mode-selector-2](https://user-images.githubusercontent.com/2337524/43620509-21d2fb5c-96a1-11e8-89c4-be9159ef36d8.png)

**Comment by eejdoowad** [comment]
Just some opinion. Feel free to ignore it:

The UI in the previews communicate some unnecessary information.

* The tab height is rather large
* The active tab top border is unnecessary. It doesn't add any information.
* Try making the inactive tab icons gray
* The border between tabs might not be necessary

**Comment by rayman89** [comment]
@pureooze 

> I guess as a new user its hard to know what magic key you need to press to see more information in the UI.

Exactly that.

I like the new iteration of the UI better than the previous one. Sorry @eejdoowad  to have such contrasting opinion but I think implementing all those suggestions would make it worse rather than improving.

>Edit: Actually I just realized that since I am using the same color to show the unselected tabs that the search results use to show the currently selected result,

I did not understand that.

**Comment by pureooze** [comment]
@rayman89 the color used for the active selection in the search results is the same color as the inactive tabs in the mode switcher.

![image](https://user-images.githubusercontent.com/2337524/43680001-83b91780-97fe-11e8-88a1-3d4f29a0d53a.png)

**Comment by pureooze** [comment]
@eejdoowad This is what it looks like with those changes:
![image](https://user-images.githubusercontent.com/2337524/43680070-2c3dc8fa-9800-11e8-898b-d9b9da979ded.png)

I like the smaller tabs and the idea to make the icons gray is good, it help contrast the active element from the inactive ones. However I dont think inverting the background colors really works well, I prefer this look:
![image](https://user-images.githubusercontent.com/2337524/43680118-4124702e-9801-11e8-9ab2-375f01651d3a.png)

However there is still the issue of the contradictory color usage. I'm a bit busy this weekend but I'll try and come up with a solution soon. :smile:

**Comment by eejdoowad** [comment]
Another possibility is making them all have white backgrounds. The active tab will have a colored icon (and possibly border).

**Comment by pureooze** [comment]
Changed it to have a white background for all the tabs. Seems to look pretty good to me. I also tried removing the top colored border but without it its sometimes difficult to tell which mode is currently selected.

![image](https://user-images.githubusercontent.com/2337524/43814556-f5e785d4-9a98-11e8-8038-33b9c8a9c0e1.png)
 
I think I am good with this look unless there are any strong objections @eejdoowad @rayman89 ?

**Comment by eejdoowad** [comment]
Looks good. We can always iterate on the design in the future.

**Comment by rayman89** [comment]
Looks good to me too. Thank you.

**Comment by eejdoowad** [comment]
Works awesome. Some ideas:

- add "cursor: pointer" to tab css
- switch modes on mouse hover (no click necessary)
- remove mode search mode
