### ISSUE TITLE
Opening another new tab when trigger saga in new tab

### ISSUE THREAD

**Issue by eason-chen-glow** [lusakasa/saka#91]
First of all, thanks for your wonderful work. I've always been looking for such a plugin.

When I try to trigger saga in the new tab page (i.e. the page that appears after pressing `cmd + t`). The saka floating bar will end up showing in another new tab, which seems to be strange. I wonder whether it's a designed behavior or a bug.

Using macOS 10.13, chrome 70.0, saka 0.17.1

Thanks a lot.

**Comment by pureooze** [comment]
Thanks for the kind words 😃

The reason Saka opens in a new tab on the new tab page is due to how the browser deals with protected URLs. The browser does not allow injecting HTML into these pages and instead Saka needs to be loaded in a separate tab. The related code can be found here: https://github.com/lusakasa/saka/blob/master/src/background_page/index.js#L20-L80

**Comment by eason-chen-glow** [comment]
Okay, for me this behavior seems weird but it seems hard to solve. Thanks for your time. I'll close this one.
